#%%

import os



rst = ["loot_pumper",\
"sea2land_fork_tro",\
"bermudatriangle",\
"piratihatitator",\
"hogusporkusator",\
"tro_oceanfish",\
"tro_schoolherd",\
"tro_blowdart",\
"tro_butterfly",\
"tro_butterflywings",\
"tro_cave_entrance",\
"tro_cave_exit",\
"tro_feathers",\
"tro_grass",\
"tro_poop",\
"tro_tumbleweedspawner",\
"tro_umbrella",\
"tro_veggies",\
"tro_walls",\
"tro_wobster",\
"wave_shimmer_tropical",\
"wave_shore_tropical",\
"house_wall",\
"sparkle_fx",\
"fx",\
"obsidianaxe",\
"armor_obsidian",\
"meteor_impact",\
"dug_cofeecactus",\
"snake",\
"snake_hole",\
"snakeskin",\
"poisonbubble",\
"venom_gland",\
"harpoon",\
"new_hats",\
"parrot_pirate",\
"dubloon",\
"machetes",\
"tunacan",\
"seagull",\
"toucan",\
"lake",\
"boatcork",\
"frogpoison",\
"mosquitopoison",\
"cormorant",\
"antivenom",\
"chiminea",\
"chimineafire",\
"armorseashell",\
"ox_horn",\
"ox",\
"oxherd",\
"knightboat_cannonshot",\
"rowboat_wake",\
"splash_water",\
"blubber",\
"fish_med",\
"debris",\
"boatrepairkit",\
"sandbag",\
"cutlass",\
"luggarechestspawn",\
"porto",\
"porto2",\
"buriedtreasure",\
"windtrail",\
"windswirl",\
"ventania",\
"sail",\
"boattorch",\
"boatlantern",\
"boatcannon",\
"woodlegs_boatcannon",\
"quackeringram",\
"quackenbeak",\
"quackendrill",\
"quackering_wave",\
"quackering_wake",\
"trawlnet",\
"boatsurf",\
"boatsurfothers",\
"boatpirate",\
"turbine_blades",\
"buoy",\
"armor_lifejacket",\
"saplingnova",\
"edgefog",\
"boatpirateamigo",\
"shadowwaxwell_boat",\
"woodlegshat",\
"telescope",\
"thatchpack",\
"parrot",\
"seagullwater",\
"seaweed_stalk",\
"corallarve",\
"nubbin",\
"coconade",\
"piratepack",\
"ox_flute",\
"blubbersuit",\
"tarsuit",\
"tarlamp",\
"waterchest",\
"mussel_bed",\
"mussel_stick",\
"messagebottle_sw",\
"bottlelantern",\
"researchlab5",\
"roe",\
"roe_fish",\
"fishfarm",\
"fishfarm_sign",\
"mussel_farm",\
"sea_chiminea",\
"tar_extractor",\
"seatrap",\
"hail",\
"wave_ripple",\
"twister_defogo",\
"twister_tornadodefogo",\
"firetwister_spawner",\
"fire_twister_seal",\
"walani",\
"wilbur",\
"woodlegs",\
"glass",\
"grass_tall",\
"asparagus",\
"deep_jungle_fern_noise",\
"vampirebatcave",\
"vampirebatcave_interior",\
"roc_cave_entrance",\
"roc_cave_interior",\
"vampitecave_deco",\
"spearlauncher",\
"spear_wathgrithr",\
"speargun",\
"jungletreeguard",\
"seataro_planted",\
"seatarospawner",\
"ox_wool",\
"conch",\
"seacucumber",\
"watercress",\
"jungletreeguard_snake",\
"armor_cactus",\
"scorpionte",\
"cork",\
"corkbat",\
"hats_hamlet",\
"sedimentpuddle",\
"flood_ice",\
"snake2",\
"bramble",\
"bramble_bulb",\
"dungball",\
"dungbeetle",\
"dungpile",\
"chitin",\
"pinkman",\
"oincpile",\
"piggolem",\
"krakenchest",\
"lavaarena_hound",\
"lavaarena_knight",\
"lavaarena_merm",\
"lavaarena_spider",\
"lavaarena_bishop",\
"frog_poison",\
"spearsw",\
"boatmetal",\
"bird_swarm",\
"birds_ham",\
"blunderbuss",\
"cloudpuff",\
"bishopwater",\
"rookwater",\
"solofish",\
"tropicalspawnblocker",\
"whaletrack",\
"swfishbait",\
"beds",\
"rug",\
"shears",\
"gold_dust",\
"goldpan",\
"icebearger",\
"icedeerclops",\
"icerockcreatures",\
"cave_exit_vulcao",\
"cave_entrance_vulcao",\
"vidanomar",\
"vidanomarseaworld",\
"ashfx",\
"boat_raft_rot",\
"nectar_pod",\
"piggravestone",\
"mangrovespawner",\
"oxwaterspawner",\
"grasswaterspawner",\
"waterreedspawner",\
"fishinholewaterspawner",\
"poisonbalm",\
"seasack",\
"magic_seal",\
"wind_conch",\
"sail_stick",\
"armor_windbreaker",\
"vine",\
"basefan",\
"floodsw",\
"birdwhistle",\
"bundled_structure",\
"tro_teleportato",\
"invisiblepondfish",\
"spider_mutators_new",\
"anthillcave",\
"anthill_cavelamp",\
"grotto_grub_nest",\
"grotto_grub",\
"grotto_parsnip",\
"grottoqueen",\
"watertree_pillar2",\
"firerain",\
"lavapool",\
"obsidian",\
"bramble_bush",\
"tidalpoolnew",\
"marsh_tree_new",\
"preparedfoods_tro",\
"collapsedchest_tro",\
"corkchest",\
"smeltingrecipecard",\
"buffs_tro",\
"whirlpool",\
"pigbanditexit",\
"porkland_sw_entrance",\
"boatraft_old",\
"boatlog_old",\
"boatraft",\
"vampirebat",\
"aporkalypse_clock",\
"hanging_vine",\
"grabbing_vine",\
"dragoonegg",\
"tigersharkpool",\
"tigersharktorch",\
"hatty_piggy_tfc",\
"boarmound",\
"roc_nest",\
"glowfly",\
"rabid_beetle",\
"obsidianstaff",\
"mermhouse_fisher",\
"mermtrader",\
"pig_scepter",\
"quagmire_mushroomstump",\
"quagmire_mushrooms",\
"quagmire_fern",\
"quagmire_pebblecrab",\
"quagmire_safe",\
"wildbeaver",\
"wildbeaver_house",\
"beaverskin",\
"quagmire_park_gate",\
"quagmire_parkspike",\
"wildbeaverguard",\
"beaver_head",\
"beavertorch",\
"quagmire_key",\
"quagmire_goatkid",\
"roc",\
"roc_leg",\
"roc_head",\
"roc_tail",\
"roc_robin_egg",\
"ro_bin_gizzard_stone",\
"ro_bin",\
"gnatmound",\
"gnat",\
"hippo_antler",\
"hippoherd",\
"hippoptamoose",\
"lillypad",\
"lotus",\
"lotus_flower",\
"bill",\
"bill_quill",\
"reeds_water",\
"obsidiancoconade",\
"obsidiancoconadeactive",\
"fabric",\
"armor_snakeskin",\
"crate",\
"dragoon",\
"dragoonfire",\
"dragoonspit",\
"dragoonden",\
"dragoonheart",\
"volcano_shrub",\
"flamegeyser",\
"rock_obsidian",\
"magma_rocks",\
"obsidian_workbench",\
"obsidianfirepit",\
"obsidianfirefire",\
"elephantcactus",\
"coffeebush",\
"coffeebeans",\
"lavaerupt",\
"volcano",\
"woodlegs_cage",\
"woodlegs_key1",\
"woodlegs_key2",\
"woodlegs_key3",\
"woodlegs_retinue",\
"woodlegsghost",\
"woodlegs_unlock",\
"vulcano",\
"escadadovulcao",\
"flup",\
"flupegg",\
"tidalpool",\
"poisonhole",\
"tigershark",\
"tigersharkshadow",\
"volcanofog",\
"flupspawner",\
"jungletrees",\
"jungletreeseed",\
"bambootree",\
"bamboo",\
"wildbore",\
"wildborehouse",\
"doydoy",\
"doydoy_mating_fx",\
"doydoyegg",\
"doydoyfeather",\
"doydoyherd",\
"doydoynest",\
"livingjungletree",\
"doydoy_spawner",\
"berrybush2_snake",\
"lavapondbig",\
"bigfoot",\
"glommerbell",\
"sweet_potato",\
"tropicalfan",\
"sand_castle",\
"sandhill",\
"sand",\
"seashell",\
"seashell_beached",\
"rock_limpet",\
"limpets",\
"palmleaf",\
"palmleafhut",\
"palmtrees",\
"coconut",\
"crab",\
"crabhole",\
"treeguard",\
"treeguard_coconut",\
"warningshadow",\
"slotmachine",\
"sharkitten",\
"sharkittenspawner",\
"bush_vine",\
"primeapebarrel",\
"monkeyball",\
"shark_gills",\
"primeape",\
"icemaker",\
"tigereye",\
"packim",\
"packim_fishbone",\
"tree_forest",\
"tree_forest_deep",\
"tree_forest_rot",\
"tree_forestseed",\
"spider_monkey_tree",\
"spider_monkey",\
"spider_monkey_herd",\
"spider_ape",\
"trapslug",\
"antman2",\
"fennel",\
"pig_palace2",\
"pig_palace2_interior",\
"peagawk_prism",\
"peagawkfeather_prism",\
"city_lamp2",\
"pig_guard_tower2",\
"wall_spawn_city",\
"spider_ape_tree",\
"slipstor",\
"slip",\
"slipstor_spawner",\
"octoatt",\
"octopus",\
"octohouse",\
"coralreef",\
"coral",\
"seaweed_planted",\
"seaweed",\
"mangrovetrees",\
"mangrovetreesbee",\
"spidercoralhole",\
"tentacleunderwater",\
"grass_water",\
"rocksunderwater",\
"wreck",\
"fishinhole",\
"octopusking",\
"kraken_tentacle",\
"kraken_projectile",\
"kraken",\
"kraken_jellyfish",\
"kraken_spawner",\
"solofish",\
"swordfish",\
"sharx",\
"stungray",\
"pirateghost",\
"redbarrel",\
"lobsterhole",\
"mussel",\
"waterygrave",\
"bioluminescence",\
"boatrowarmored",\
"boatrowcargo",\
"rawling",\
"coral_brain_rock",\
"coral_brain",\
"limestone",\
"shark_fin",\
"rainbowjellyfish",\
"rainbowjellyfish_planted",\
"sea_yard",\
"sea_yard_arms_fx",\
"tar",\
"tar_pool",\
"bioluminescence_spawner",\
"boatrow",\
"flotsam_debris_sw",\
"boatrowencrusted",\
"ballphin",\
"ballphinhouse",\
"dorsalfin",\
"ballphinpod",\
"jellyfish",\
"jellyfish_planted",\
"crocodog_spawner",\
"crocodog",\
"whale",\
"whale_carcass",\
"knightboat",\
"poisonmistparticle",\
"deco_util",\
"deco_util2",\
"deco_room_window",\
"deco_swinging_light",\
"deco_lightglow",\
"pig_shop_spears",\
"topiary",\
"lawnornaments",\
"hedge",\
"clippings",\
"city_lamp",\
"hamlet_cones",\
"securitycontract",\
"city_hammer",\
"magnifying_glass",\
"pigbandit",\
"banditmap",\
"pig_shop",\
"pig_shop_produce_interior",\
"pig_shop_hoofspa_interior",\
"pig_shop_general_interior",\
"pig_shop_florist_interior",\
"pig_shop_deli_interior",\
"pig_shop_academy_interior",\
"pig_shop_cityhall_interior",\
"pig_shop_cityhall_player_interior",\
"pig_shop_hatshop_interior",\
"pig_shop_weapons_interior",\
"pig_shop_bank_interior",\
"pig_shop_arcane_interior",\
"pig_shop_antiquities_interior",\
"pig_shop_tinker_interior",\
"pig_palace_interior",\
"pig_palace",\
"pigman_shopkeeper_desk",\
"shop_pedestals",\
"deed",\
"playerhouse_city_interior",\
"shelf",\
"shelf_slot",\
"trinkets_giftshop",\
"key_to_city",\
"wallpaper",\
"player_house_kits",\
"player_house",\
"pigman_city",\
"pighouse_city",\
"pig_guard_tower",\
"armor_metal",\
"reconstruction_project",\
"water_spray",\
"water_pipe",\
"sprinkler1",\
"alloy",\
"smelter",\
"halberd",\
"oinc",\
"oinc10",\
"oinc100",\
"porklandintro",\
"twister",\
"twister_spawner",\
"twister_seal",\
"twister_tornado",\
"chicken",\
"chickenhouse",\
"peekhen",\
"peekhenspawner",\
"crabapple_tree",\
"zeb",\
"wildboreking",\
"wildbore_minion",\
"wildborekingstaff",\
"wildboreking_spawner",\
"rainforesttrees",\
"rainforesttree_sapling",\
"meteor_impact",\
"tuber",\
"tubertrees",\
"pangolden",\
"thunderbird",\
"thunderbirdnest",\
"ancient_robots",\
"ancient_hulk",\
"ancient_herald",\
"armor_vortex_cloak",\
"armor_void_cloak",\
"herald_tatters",\
"living_artifact",\
"rock_basalt",\
"ancient_robots_assembly",\
"laser_ring",\
"laser",\
"iron",\
"pheromonestone",\
"pig_ruins_maze_old",\
"pig_ruins_mazecompact",\
"pig_ruins_maze",\
"anthill_interior",\
"anthill_lamp",\
"anthill_stalactite",\
"antchest",\
"antcombhome",\
"antcombhomecave",\
"giantgrub",\
"antqueen",\
"rocksham",\
"deco_ruins_fountain",\
"pig_ruins_entrance_interior",\
"pig_ruins_entrance",\
"pig_ruins_dart_statue",\
"pig_ruins_dart",\
"pig_ruins_creeping_vines",\
"pig_ruins_pressure_plate",\
"pig_ruins_spear_trap",\
"smashingpot",\
"pig_ruins_light_beam",\
"littlehammer",\
"relics",\
"gascloud",\
"bugrepellent",\
"teatree_nut",\
"teatrees",\
"piko",\
"clawpalmtrees",\
"clawpalmtree_sapling",\
"bugfood",\
"rock_flippable",\
"peagawkfeather",\
"peagawk",\
"aloe",\
"pog",\
"weevole",\
"weevole_carapace",\
"armor_weevole",\
"pugalisk",\
"pugalisk_trap_door",\
"pugalisk_ruins_pillar",\
"pugalisk_fountain",\
"pugalisk_fountain_made",\
"waterdrop",\
"floweroflife",\
"gaze_beam",\
"snake_bone",\
"mandrakehouse",\
"mandrakeman",\
"jungle_border_vine",\
"light_rays_ham",\
"nettle",\
"nettle_plant",\
"rainforesttrees",\
"rainforesttree_sapling",\
"tree_pillar",\
"flower_rainforest",\
"pig_ruins_torch",\
"mean_flytrap",\
"radish",\
"adult_flytrap",\
"antman_warrior_egg",\
"antman_warrior",\
"antman",\
"antlarva",\
"anthill",\
"antsuit",\
"venus_stalk",\
"walkingstick",\
"cloudpuff",\
]


current_file_path = os.getcwd()
tropical_adventrues_root_path = os.path.dirname(current_file_path) # 获得热带冒险mod的根目录
tropical_adventrues_root_path = tropical_adventrues_root_path.replace("\docs", "") 
tropical_adventrues_prefabs_path = tropical_adventrues_root_path + r"\prefabs"


print("热带冒险根目录：", tropical_adventrues_root_path, )

print("热带冒险prefabs目录：", tropical_adventrues_prefabs_path)



#%%
def check_and_rename_files(folder_path, valid_names):
    """
    检查文件夹中的文件名称是否在给定列表中，如果不在且不包含'util'字样，则重命名文件。
    
    :param folder_path: 文件夹路径
    :param valid_names: 有效文件名称列表
    """
    # 获取文件夹中的所有文件
    files = os.listdir(folder_path)
    
    for file in files:
        file_path = os.path.join(folder_path, file)
        
        # 检查文件是否为文件（排除文件夹）
        if os.path.isfile(file_path):
            # 检查文件名称是否在有效列表中
            if file.replace(".lua", "")  not in valid_names:
                # 检查文件名称是否包含'util'字样
                if 'util' not in file and "def" not in file and "tool" not in file :
                    # 生成新的文件名称
                    new_file_name = f"renamed_{file}"
                    new_file_path = os.path.join(folder_path, new_file_name)
                    
                    # 重命名文件
                    os.rename(file_path, new_file_path)
                    print(f"重命名文件: {file} -> {new_file_name}")


check_and_rename_files(tropical_adventrues_prefabs_path, rst)
# %%
